# Generated by Django 5.0.3 on 2026-08-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64)),
                ('key_hash', models.CharField(max_length=64)),
                ('window_started_at', models.DateTimeField()),
                ('window_expires_at', models.DateTimeField(db_index=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scope', 'key_hash'],
                'indexes': [models.Index(fields=['scope', 'window_expires_at'], name='abuse_scope_window_idx'), models.Index(fields=['scope', 'blocked_until'], name='abuse_scope_block_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='abusecounter',
            constraint=models.UniqueConstraint(fields=('scope', 'key_hash'), name='abuse_scope_key_uniq'),
        ),
    ]
