# Generated by Django 5.0.3 on 2026-08-30 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0017_authsession_usertoken_auth_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('MFA_SUCCESS', 'MFA success'), ('MFA_FAILURE', 'MFA failure'), ('SESSION_CREATED', 'Session created'), ('SESSION_REVOKED', 'Session revoked'), ('LOGOUT', 'Logout'), ('LOGOUT_ALL', 'Logout all'), ('TOKEN_REFRESHED', 'Token refreshed'), ('REFRESH_REPLAY_DETECTED', 'Refresh replay detected'), ('PASSWORD_RESET_REQUESTED', 'Password reset requested'), ('PASSWORD_RESET_COMPLETED', 'Password reset completed'), ('INACTIVE_USER_DENIED', 'Inactive user denied'), ('SESSION_ACCESS_DENIED', 'Session access denied')], max_length=64)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('DENIED', 'Denied'), ('REVOKED', 'Revoked')], max_length=16)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('request_method', models.CharField(blank=True, default='', max_length=16)),
                ('request_path', models.CharField(blank=True, default='', max_length=512)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('auth_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='user.authsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='sec_event_created_idx'), models.Index(fields=['event_type', 'created_at'], name='sec_event_type_created_idx'), models.Index(fields=['user', 'created_at'], name='sec_event_user_created_idx'), models.Index(fields=['auth_session', 'created_at'], name='sec_event_session_created_idx'), models.Index(fields=['severity', 'created_at'], name='sec_event_sev_created_idx')],
            },
        ),
    ]
