# Generated by Django 5.0.3 on 2026-08-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('MFA_SUCCESS', 'MFA success'), ('MFA_FAILURE', 'MFA failure'), ('MFA_ENABLED', 'MFA enabled'), ('MFA_DISABLED', 'MFA disabled'), ('MFA_CHANGE_DENIED', 'MFA change denied'), ('SESSION_CREATED', 'Session created'), ('SESSION_REVOKED', 'Session revoked'), ('LOGOUT', 'Logout'), ('LOGOUT_ALL', 'Logout all'), ('TOKEN_REFRESHED', 'Token refreshed'), ('REFRESH_REPLAY_DETECTED', 'Refresh replay detected'), ('PASSWORD_CHANGE_SUCCESS', 'Password change success'), ('PASSWORD_CHANGE_FAILURE', 'Password change failure'), ('PASSWORD_CHANGE_THROTTLED', 'Password change throttled'), ('PASSWORD_CHANGE_BLOCKED', 'Password change blocked'), ('REAUTH_SUCCESS', 'Reauthentication success'), ('REAUTH_FAILURE', 'Reauthentication failure'), ('PASSWORD_RESET_REQUESTED', 'Password reset requested'), ('PASSWORD_RESET_COMPLETED', 'Password reset completed'), ('ACCOUNT_DISABLED', 'Account disabled'), ('INACTIVE_USER_DENIED', 'Inactive user denied'), ('SESSION_ACCESS_DENIED', 'Session access denied'), ('LOGIN_THROTTLED', 'Login throttled'), ('LOGIN_BLOCKED', 'Login blocked'), ('OTP_THROTTLED', 'OTP throttled'), ('OTP_BLOCKED', 'OTP blocked'), ('PASSWORD_RESET_THROTTLED', 'Password reset throttled'), ('PASSWORD_RESET_BLOCKED', 'Password reset blocked'), ('REAUTH_THROTTLED', 'Reauthentication throttled'), ('REAUTH_BLOCKED', 'Reauthentication blocked'), ('MFA_CHANGE_THROTTLED', 'MFA change throttled'), ('MFA_CHANGE_BLOCKED', 'MFA change blocked')], max_length=64),
        ),
    ]
