# Generated by Django 5.0.3 on 2026-09-05 02:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_key', models.CharField(max_length=128, unique=True)),
                ('domain', models.CharField(choices=[('IDENTITY', 'Identity'), ('SESSION', 'Session'), ('MFA', 'Multi-factor authentication'), ('ASSURANCE', 'Authentication assurance'), ('ABUSE_CONTROL', 'Abuse control'), ('AUDIT', 'Audit'), ('AUTHORIZATION', 'Authorization'), ('DATA_PROTECTION', 'Data protection'), ('DATABASE', 'Database'), ('INFRASTRUCTURE', 'Infrastructure'), ('BACKUP_RECOVERY', 'Backup & recovery'), ('INCIDENT_RESPONSE', 'Incident response'), ('MONITORING', 'Monitoring'), ('SECURE_SDLC', 'Secure SDLC'), ('VULNERABILITY_MANAGEMENT', 'Vulnerability management'), ('GOVERNANCE', 'Governance'), ('VENDOR_RISK', 'Vendor risk'), ('COMPLIANCE_EVIDENCE', 'Compliance evidence'), ('AGENT_SECURITY', 'Agent security')], max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('control_type', models.CharField(choices=[('LIVE', 'Live'), ('PERIODIC', 'Periodic'), ('DOCUMENTARY', 'Documentary'), ('MANUAL', 'Manual')], max_length=32)),
                ('lifecycle', models.CharField(choices=[('IMPLEMENTED', 'Implemented'), ('PLANNED', 'Planned'), ('DEPRECATED', 'Deprecated')], default='IMPLEMENTED', max_length=32)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('NEEDS_ATTENTION', 'Needs attention'), ('CONTROL_FAILURE', 'Control failure'), ('UNKNOWN', 'Unknown'), ('NOT_APPLICABLE', 'Not applicable')], default='UNKNOWN', max_length=32)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('severity_if_failed', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='WARNING', max_length=16)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('last_evidence_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain', 'control_key'],
                'indexes': [models.Index(fields=['domain', 'status'], name='sec_ctrl_domain_status_idx'), models.Index(fields=['status'], name='sec_ctrl_status_idx'), models.Index(fields=['control_type'], name='sec_ctrl_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('SECURITY_EVENT', 'Security event'), ('AUTOMATED_TEST', 'Automated test'), ('CI_RESULT', 'CI result'), ('CONFIGURATION_CHECK', 'Configuration check'), ('MANUAL_VERIFICATION', 'Manual verification'), ('POLICY_REVIEW', 'Policy review'), ('RISK_ASSESSMENT', 'Risk assessment'), ('BACKUP_TEST', 'Backup test'), ('RESTORE_TEST', 'Restore test'), ('VULNERABILITY_SCAN', 'Vulnerability scan'), ('PENETRATION_TEST', 'Penetration test'), ('VENDOR_REVIEW', 'Vendor review'), ('INCIDENT_EXERCISE', 'Incident exercise'), ('OTHER', 'Other')], max_length=64)),
                ('source_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_name', models.CharField(blank=True, default='', max_length=160)),
                ('source_reference', models.CharField(blank=True, default='', max_length=256)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True, default='')),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('WARNING', 'Warning'), ('INFORMATIONAL', 'Informational')], max_length=32)),
                ('observed_at', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='security.securitycontrol')),
            ],
            options={
                'ordering': ['-observed_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_key', models.CharField(max_length=160, unique=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('ACCEPTED_RISK', 'Accepted risk'), ('FALSE_POSITIVE', 'False positive')], default='OPEN', max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('expected_behavior', models.TextField(blank=True, default='')),
                ('observed_behavior', models.TextField(blank=True, default='')),
                ('affected_system', models.CharField(blank=True, default='', max_length=160)),
                ('affected_component', models.CharField(blank=True, default='', max_length=160)),
                ('source_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_reference', models.CharField(blank=True, default='', max_length=256)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='security.securitycontrol')),
                ('evidence', models.ManyToManyField(blank=True, related_name='findings', to='security.securityevidence')),
                ('related_events', models.ManyToManyField(blank=True, related_name='findings', to='security.securityevent')),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='securityevidence',
            index=models.Index(fields=['control', 'observed_at'], name='sec_evid_ctrl_observed_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevidence',
            index=models.Index(fields=['evidence_type', 'observed_at'], name='sec_evid_type_observed_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevidence',
            index=models.Index(fields=['result', 'observed_at'], name='sec_evid_result_obs_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevidence',
            index=models.Index(fields=['source_type', 'source_name'], name='sec_evid_source_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevidence',
            index=models.Index(fields=['observed_at'], name='sec_evid_observed_idx'),
        ),
        migrations.AddIndex(
            model_name='securityfinding',
            index=models.Index(fields=['status', 'severity'], name='sec_find_status_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='securityfinding',
            index=models.Index(fields=['control', 'status'], name='sec_find_ctrl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='securityfinding',
            index=models.Index(fields=['last_seen_at'], name='sec_find_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='securityfinding',
            index=models.Index(fields=['affected_system'], name='sec_find_system_idx'),
        ),
    ]
