# Generated by Django 5.0.3 on 2024-03-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_usertoken_user_id_usertoken_is_revoked_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=26)),
                ("token", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="token",
            field=models.CharField(
                help_text="The unique token string.", max_length=100, unique=True
            ),
        ),
    ]
