# Generated by Django 5.0.3 on 2024-03-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_reset_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
