# Generated by Django 5.0.3 on 2024-03-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reset",
            name="email",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="reset",
            name="token",
            field=models.CharField(
                help_text="The unique token string.", max_length=512, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="token",
            field=models.CharField(
                help_text="The unique token string.", max_length=512, unique=True
            ),
        ),
    ]
