# Generated by Django 5.0.3 on 2024-03-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_reset_email_alter_reset_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tfa_secret",
            field=models.CharField(default="", max_length=255),
        ),
    ]
