# Generated by Django 5.0.3 on 2024-03-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_customuser_tfa_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
