# Generated by Django 5.0.3 on 2024-03-31 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_customuser_is_2fa_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Enter your email address. Used for login.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                help_text="Enter your first name.",
                max_length=26,
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_2fa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Check this if you wish to enable two-factor authentication.",
                verbose_name="Is 2FA Enabled",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                help_text="Enter your last name.",
                max_length=26,
                verbose_name="Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                help_text="Enter a secure password.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="tfa_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Secret key for two-factor authentication. Leave blank if unsure.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="reset",
            name="email",
            field=models.CharField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="reset",
            name="token",
            field=models.CharField(max_length=512, unique=True, verbose_name="Token"),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when this token was created.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="expired_at",
            field=models.DateTimeField(
                help_text="The date and time when this token will expire.",
                verbose_name="Expires At",
            ),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="is_revoked",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this token has been revoked.",
                verbose_name="Is Revoked",
            ),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="last_used_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The last date and time this token was used.",
                verbose_name="Last Used At",
            ),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="token",
            field=models.CharField(
                help_text="The actual token string. Must be unique.",
                max_length=512,
                unique=True,
                verbose_name="Token",
            ),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this token.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.CreateModel(
            name="TemporarySecurityToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="A unique token string for temporary access or operations.",
                        max_length=100,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this token was generated.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="The date and time when this token becomes invalid and cannot be used.",
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user to whom this temporary token is associated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
