# Generated by Django 5.0.3 on 2024-04-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_reset_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                help_text="Enter a secure password.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="temporarysecuritytoken",
            name="token",
            field=models.CharField(
                help_text="A unique token string for temporary access or operations.",
                max_length=512,
                unique=True,
                verbose_name="Token",
            ),
        ),
    ]
