# Generated by Django 5.0.3 on 2024-05-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_alter_customuser_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
