# Generated by Django 5.0.3 on 2024-06-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_customuser_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_2fa_setup_in_progress",
            field=models.BooleanField(
                default=False,
                help_text="Tracks whether the 2Fa setup process is ongoing",
                verbose_name="Is 2FA Setup in Progress",
            ),
        ),
    ]
