# Generated by Django 5.0.3 on 2025-06-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_customuser_is_2fa_setup_in_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("physician", "Physician"),
                    ("technologist", "Technologist"),
                ],
                default="technologist",
                help_text="User's role in the system (admin, physician, technologist).",
                max_length=20,
            ),
        ),
    ]
