# Generated by Django 5.0.3 on 2026-08-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_authsession_usertoken_auth_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authsession',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
